M48
; DRILL file {KiCad 7.0.1} date Thu 30 Mar 2023 04:52:30 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-30T16:52:30-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1378
%
G90
G05
T1
X2.2087Y-4.5807
X2.5236Y-4.5807
T2
X2.1811Y-2.1299
X2.8811Y-2.1299
T3
X2.1811Y-3.9299
X2.8811Y-3.9299
T4
X2.3937Y-3.2189
T0
M30
